### PR TITLE
Version 0.4.0

### PR DESCRIPTION
**Pull request by afck**

### CODE REVIEW

**Comment by dirvine** [comment]
I wonder if  #103 should be included in this release? IT would appear to make sense.

**Comment by ravinderjangra** [comment]
hey, any plan on merging this 😄 ?

**Comment by afck** [comment]
@igorbarinov: Can I merge this and publish version 0.4.0?

**Comment by igorbarinov** [comment]
If you feel like this please do. I have no objections.

**Comment by afck** [comment]
Looks like I still can't merge. You probably have to approve it, @igorbarinov.

**Comment by ravinderjangra** [comment]
Any update on this?

**Comment by afck** [comment]
Thank you! It's [published](https://crates.io/crates/threshold_crypto/0.4.0) now.

**Pull request merged**
