### PR TITLE
Implement common traits for SerdeSecret

### PR DESCRIPTION
**Pull request by sgeisler**
Implement `Debug`, `Eq`, `PartialEq` and Clone for `SerdeSecret` if they
are implemented for the inner type.

### CODE REVIEW

**Comment by sgeisler** [comment]
The problem is for that to work I had to require them for the inner type `T` too which propagates to other impls for `SerdeSecret<T>`. I tried that first and ended up writing `T: Debug + Eq + Clone` far too often.

**Comment by afck** [comment]
Really? Isn't
```rust
#[derive(Debug)]
struct S<T> { … };
```
equivalent to `impl<T: Debug> Debug for S<T>`, i.e. doesn't `derive` include these trait bounds automatically?

**Comment by sgeisler** [comment]
I'd have to check again, but I tried that first and it threw some errors.

**Comment by afck** [comment]
I tried it out, and it's equivalent:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0664131fac92330bb8388ebb21682eaf
I'd prefer to use `derive` then.

**Comment by sgeisler** [comment]
Fixed it.

I should have tested ´threshold_crypto´ on it's own, the errors I got were probably from the project I was using it in as a dependency.

**Pull request merged**
